### ISSUE TITLE
Python 3.3.x で動作しない (was:エラー報告)

### ISSUE THREAD

**Issue by kyouryuukunn** [koron/online-update#4]
ブログで配布していたvim7.4用のアップデートファイルですが以下のようなエラーが出たので報告します。

```
Found update.
 * 1/2  Download  [Traceback (most recent call last):                ]
  File "E:\Soft\vim\vim-online-update.py", line 75, in <module>
    retval = update(sys.argv[1])
  File "E:\Soft\vim\vim-online-update.py", line 60, in update
    result = updater.update()
  File "E:\Soft\vim\online_updater\__init__.py", line 43, in update
    if downloader.download():
  File "E:\Soft\vim\online_updater\downloader.py", line 79, in download
    self._save_as(response, tmp)
  File "E:\Soft\vim\online_updater\downloader.py", line 51, in _save_as
    max = int(response.info().getheader('Content-Length', -1))
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
約10秒後にこのウィンドウは自動的に閉じます。
```

**Comment by koron** [comment]
@kyouryuukunn 使ってるPythonのバージョンを教えてもらえますか?

**Comment by kyouryuukunn** [comment]
python3.31です。

**Comment by koron** [comment]
@kyouryuukunn ありがとうございます。こちらでも3.3.2で失敗することを確認できました。

とりあえずpython 2.7.x系で使っておいてください。

**Comment by koron** [comment]
3.3.2 と 2.7.4 で動作確認しました at 876a201853031a293eefab5290fcaab8b5d2f819

**Comment by koron** [comment]
@kyouryuukunn 配布しているZIPを最新版に差し替えました。お時間のあるときに 3.3.X でお試しください。

**Comment by kyouryuukunn** [comment]
2013/08/14版を試しましたが、残念ながらまだエラーが出ました。
- 2/2  Extract   [=========Traceback (most recent call last):       ]
  File "E:\Soft\vim\vim-online-update.py", line 75, in <module>
    retval = update(sys.argv[1])
  File "E:\Soft\vim\vim-online-update.py", line 60, in update
    result = updater.update()
  File "E:\Soft\vim\online_updater__init__.py", line 55, in update
    if extractor.extractAll():
  File "E:\Soft\vim\online_updater\extractor.py", line 270, in extractAll
    for op in optimizer.operations():
  File "E:\Soft\vim\online_updater\extractor.py", line 101, in operations
    if not knownTable.has_key(i.name):
  AttributeError: 'dict' object has no attribute 'has_key'

**Comment by koron** [comment]
もっかい最新版で試してみてください。

**Comment by kyouryuukunn** [comment]
成功しました。

**Comment by koron** [comment]
@kyouryuukunn 動作確認、ありがとうございます!
